// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6OuOKG_oyDFHuw4itS--03rnTEdzWN-Y',
    appId: '1:145085006519:web:82434802c13c6139298332',
    messagingSenderId: '145085006519',
    projectId: 're-exam-cb724',
    authDomain: 're-exam-cb724.firebaseapp.com',
    storageBucket: 're-exam-cb724.appspot.com',
    measurementId: 'G-55L710HLSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4DNN6Rgh9NgP9liAOmeGiOPEELmhtAzU',
    appId: '1:145085006519:android:bc5445aa55e026f8298332',
    messagingSenderId: '145085006519',
    projectId: 're-exam-cb724',
    storageBucket: 're-exam-cb724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj3Rb4Xi3DSi5HDrm3N65mCleUVJMV8S0',
    appId: '1:145085006519:ios:9794bc60f9196d8e298332',
    messagingSenderId: '145085006519',
    projectId: 're-exam-cb724',
    storageBucket: 're-exam-cb724.appspot.com',
    iosBundleId: 'com.example.reExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj3Rb4Xi3DSi5HDrm3N65mCleUVJMV8S0',
    appId: '1:145085006519:ios:9794bc60f9196d8e298332',
    messagingSenderId: '145085006519',
    projectId: 're-exam-cb724',
    storageBucket: 're-exam-cb724.appspot.com',
    iosBundleId: 'com.example.reExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6OuOKG_oyDFHuw4itS--03rnTEdzWN-Y',
    appId: '1:145085006519:web:7be1a9a70808fe95298332',
    messagingSenderId: '145085006519',
    projectId: 're-exam-cb724',
    authDomain: 're-exam-cb724.firebaseapp.com',
    storageBucket: 're-exam-cb724.appspot.com',
    measurementId: 'G-JPLHW655P7',
  );
}
